"""Generate structural documentation directly from the shared SQLAlchemy schema."""
from pathlib import Path

from sqlalchemy import CheckConstraint, UniqueConstraint
from sqlalchemy.dialects import postgresql

from .schema import metadata
from .console import message

OUTPUT = Path(__file__).resolve().parents[2] / 'docs' / 'database-schema.md'


def render():
    lines = ['# Database schema', '',
        'Generated from `shared/database/schema.py`. Do not edit this file directly.', '',
        'Regenerate: `python sandbox-data/manage.py schema-docs`.', '',
        'Change workflow: [database-workflow.md](database-workflow.md).', '',
        '## Relationships', '', '```mermaid', 'erDiagram']
    for table in metadata.sorted_tables:
        lines.append(f'    {table.name} {{')
        for column in table.primary_key:
            lines.append(f'        {column.type.__class__.__name__} {column.name} PK')
        lines.append('    }')
        for constraint in sorted(table.foreign_key_constraints, key=lambda item: str(item.elements[0].target_fullname)):
            target = constraint.elements[0].column.table.name
            labels = ', '.join(element.parent.name for element in constraint.elements)
            columns = {element.parent.name for element in constraint.elements}
            unique_keys = [{column.name for column in table.primary_key}]
            unique_keys += [{column.name for column in item.columns} for item in table.constraints
                if isinstance(item, UniqueConstraint)]
            relationship = '||--o|' if columns in unique_keys else '||--o{'
            lines.append(f'    {target} {relationship} {table.name} : "{labels}"')
    lines += ['```', '']
    for table in metadata.sorted_tables:
        lines += [f'## {table.name}', '', table.info.get('description', ''), '',
            '| Column | PostgreSQL type | Nullable | Key / reference | Default | Meaning |',
            '| --- | --- | --- | --- | --- | --- |']
        for column in table.columns:
            keys = ['PK'] if column.primary_key else []
            keys += [f'FK → {fk.target_fullname}' for fk in sorted(column.foreign_keys, key=lambda fk: fk.target_fullname)]
            default = str(column.server_default.arg) if column.server_default is not None else ''
            description = column.info.get('description', '')
            values = [column.name, str(column.type.compile(dialect=postgresql.dialect())),
                'yes' if column.nullable else 'no', ', '.join(keys), default, description]
            lines.append('| ' + ' | '.join(value.replace('|', '\\|').replace('\n', ' ') for value in values) + ' |')
        constraints = []
        for constraint in table.constraints:
            if isinstance(constraint, CheckConstraint):
                constraints.append(f'CHECK: `{constraint.sqltext}`')
            elif isinstance(constraint, UniqueConstraint):
                detail = ', '.join(column.name for column in constraint.columns)
                if constraint.deferrable:
                    detail += f'; DEFERRABLE INITIALLY {constraint.initially}'
                constraints.append(f'UNIQUE: `{detail}`')
        for index in table.indexes:
            constraints.append(f'INDEX `{index.name}`: ' + ', '.join(column.name for column in index.columns))
        if constraints:
            lines += ['', *('- ' + constraint for constraint in sorted(constraints))]
        lines.append('')
    return '\n'.join(lines)


def write_documentation(*, check=False):
    content = render()
    if check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
            raise ValueError('Database documentation is stale. Run python manage.py schema-docs and commit the result.')
        message('  Schema documentation  up to date')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding='utf-8')
        message(f'  Generated docs/{OUTPUT.name}')
