"""Demo payer definitions with permanent codes and separate editable labels.

Keep codes/source aliases unchanged when renaming display names. Adding a row
only adds references; historical coverage is updated solely by a separate scope.
"""
PAYER_REFERENCES = ({'code': '8dcb8e0d-9c2e-53e8-8161-16702ff909af',
  'name': 'Traditional Medicare',
  'payer_type_code': 'Medicare',
  'type_name': 'Medicare',
  'source_type': 'Medicare',
  'source_name': 'Traditional Medicare'},
 {'code': '835d209a-f5ef-50e7-9553-efa4479142ec',
  'name': 'Apex Commercial Medicare',
  'payer_type_code': 'Medicare Advantage',
  'type_name': 'Commercial Medicare',
  'source_type': 'Medicare Advantage',
  'source_name': 'Apex Commercial Medicare'},
 {'code': 'dad94883-32f9-5098-8ec8-d5b4bea7bfc1',
  'name': 'Northstar Senior Health',
  'payer_type_code': 'Medicare Advantage',
  'type_name': 'Commercial Medicare',
  'source_type': 'Medicare Advantage',
  'source_name': 'Northstar Senior Health'},
 {'code': '4ac470f7-faad-5085-865a-7eeddc006454',
  'name': 'Summit Medicare',
  'payer_type_code': 'Medicare Advantage',
  'type_name': 'Commercial Medicare',
  'source_type': 'Medicare Advantage',
  'source_name': 'Summit Medicare'},
 {'code': '8cd82739-3ad7-5af1-97bc-0e3329481a67',
  'name': 'Harbor Medicare HMO',
  'payer_type_code': 'Medicare HMO',
  'type_name': 'Medicare HMO',
  'source_type': 'Medicare HMO',
  'source_name': 'Harbor Medicare HMO'},
 {'code': '313ac21a-9286-5f1c-9ed5-7c404da529d7',
  'name': 'Summit Medicare HMO',
  'payer_type_code': 'Medicare HMO',
  'type_name': 'Medicare HMO',
  'source_type': 'Medicare HMO',
  'source_name': 'Summit Medicare HMO'},
 {'code': 'd505095f-4d84-5d2f-b361-3924913d582d',
  'name': 'Evergreen Health Plan',
  'payer_type_code': 'Managed Medicaid',
  'type_name': 'Managed Medicaid',
  'source_type': 'Managed Medicaid',
  'source_name': 'Evergreen Health Plan'},
 {'code': 'd6179483-bac1-5c01-8709-226c9688f8f1',
  'name': 'Cedar State Health',
  'payer_type_code': 'Managed Medicaid',
  'type_name': 'Managed Medicaid',
  'source_type': 'Managed Medicaid',
  'source_name': 'Cedar State Health'},
 {'code': '3518dfed-f2ef-5493-86cf-7ff73a9be69e',
  'name': 'Horizon Community Care',
  'payer_type_code': 'Managed Medicaid',
  'type_name': 'Managed Medicaid',
  'source_type': 'Managed Medicaid',
  'source_name': 'Horizon Community Care'},
 {'code': 'bba3a5db-da36-5984-897e-02b91b9e5a39',
  'name': 'State Medicaid Program',
  'payer_type_code': 'Medicaid',
  'type_name': 'Medicaid',
  'source_type': 'Medicaid',
  'source_name': 'State Medicaid Program'},
 {'code': 'de62569d-b93e-50fc-a3c9-a1d68b4c5803',
  'name': 'Harborlight Hospice',
  'payer_type_code': 'Hospice',
  'type_name': 'Hospice',
  'source_type': 'Hospice',
  'source_name': 'Harborlight Hospice'},
 {'code': '23597243-4cab-5562-b924-11f5f697a8e5',
  'name': 'Willow Path Hospice',
  'payer_type_code': 'Hospice',
  'type_name': 'Hospice',
  'source_type': 'Hospice',
  'source_name': 'Willow Path Hospice'},
 {'code': '70657ceb-527a-5aaf-ad54-a61645ba3254',
  'name': 'Private Pay',
  'payer_type_code': 'Private Pay',
  'type_name': 'Private Pay',
  'source_type': 'Private Pay',
  'source_name': 'Private Pay'})
