"""Completeness for the Clinical reports, from the seeder's checkpoints: a range
is readable only when every source it reads has every day of it. A day with no
events is zero; a day never generated is a 409."""
from datetime import date

from sqlalchemy import func, select
from sqlalchemy.engine import Connection

from shared.database.schema import daily_runs
from ..common.errors import ApiError


def generated(connection: Connection, generators: tuple[str, ...], start: date, end: date) -> bool:
    """Every day from start to end generated by each of the generators."""
    days = (end - start).days + 1
    return all(connection.scalar(select(func.count()).select_from(daily_runs).where(
        daily_runs.c.generator == generator, daily_runs.c.simulation_date.between(start, end))) == days
        for generator in generators)


def require_generated(connection: Connection, generators: tuple[str, ...], start: date, end: date):
    if not generated(connection, generators, start, end):
        raise ApiError('summary_unavailable', 'The requested period includes days not generated yet. '
            'Run the seeder update or select completed dates.', 409)


def latest_day(connection: Connection) -> date:
    """The latest simulated day: what "still open" is judged on."""
    return connection.scalar(select(func.max(daily_runs.c.simulation_date)).where(daily_runs.c.generator == 'adt'))
