"""Hospital Transfers: residents sent from the facility to a hospital in a date
range, per facility, for the page to sum and divide at any drilldown level, and
broken down by payer and by reason.

Read from transfer_logs, the seeder's record of every hospital transfer: the
same transfers the Discharges report counts, with the reason, payer, days since
admission and admission source the clinical reports cut them by. Length of stay
is the days from admission to the transfer. Within 30 days means no more than
30 days after admission. A rehospitalization is the subset that came from a
hospital: admitted from one and sent back within 30 days.

The rate is transfers per 1,000 resident days. Resident days are each day's
closing census summed over the range, as the census reports count census days.

Payer types and reasons filter the report. Each breakdown applies the other
filter but not its own, so it keeps every slice to click, as the Admissions payer
donut does; everything else applies both. Payer types narrow resident days too,
so a payer's rate divides by that payer's days; reasons do not, since every
resident could be transferred for any reason.

Prior transfers are the same count over the same number of days just before the
range, with the same filters, as Admissions compares with its prior period; null
when those days were never generated.

Completeness comes from the seeder's checkpoints: a range with a day never
generated is a 409, a day with no transfers is zero.
"""
from datetime import date, timedelta
from uuid import UUID
from typing import Literal

from pydantic import BaseModel, Field
from sqlalchemy import and_, func, select
from sqlalchemy.engine import Connection

from shared.database.schema import (
    TRANSFER_REASONS, daily_payer_census_facts as census, daily_runs, payers, transfer_logs as transfers)
from ..common.dates import DateRange
from ..common.errors import ApiError
from ..common.locations import LocationSelection, facility_locations

# Transfers from their log; resident days from the census summary.
GENERATORS = ('transfer_logs', 'net_change_summary')
WITHIN_DAYS = 30


class FacilityTransfers(BaseModel):
    facility_id: str
    facility_name: str
    state: str
    portfolio: str
    region: str
    transfers: int = Field(description='Discharges to a hospital in the range.')
    within_30_days: int = Field(description='Of those, transferred no more than 30 days after admission.')
    los_days: int = Field(description='Days from admission to transfer, summed. Divide by transfers.')
    rehospitalizations: int = Field(description='Admitted from a hospital and transferred back within 30 days.')
    resident_days: int = Field(description='Closing census summed over the range. Transfers per 1,000 '
        'resident days is transfers / resident_days * 1000.')
    prior_transfers: int | None = Field(description='The same count over the same number of days just before '
        'the range, with the same filters; null when those days were never generated.')
    payers: dict[str, int] = Field(description='Transfers by payer type on the day of transfer.')
    reasons: dict[str, int] = Field(description='Transfers by clinical reason.')


class HospitalTransfers(BaseModel):
    start_date: date
    end_date: date
    prior_start_date: date
    prior_end_date: date
    items: list[FacilityTransfers]


PayerType = Literal['medicare', 'managed_medicare_pdpm', 'managed_medicare_ppo', 'medicaid', 'private',
    'hospice', 'va']


class TransfersQuery(DateRange):
    # Empty means every payer type, every reason.
    payer_types: list[PayerType] = Field(default_factory=list, max_length=20)
    reasons: list[Literal[TRANSFER_REASONS]] = Field(default_factory=list, max_length=20)


def _generated(connection: Connection, start: date, end: date) -> bool:
    """Every day from start to end generated by both sources, by their checkpoints."""
    days = (end - start).days + 1
    return all(connection.scalar(select(func.count()).select_from(daily_runs).where(
        daily_runs.c.generator == generator, daily_runs.c.simulation_date.between(start, end))) == days
        for generator in GENERATORS)


def _filters(query: TransfersQuery, skip: str | None = None):
    """The query's filters on transfer rows, less the one a breakdown shows."""
    conditions = []
    if query.payer_types and skip != 'payers':
        conditions.append(transfers.c.payer_id.in_(select(payers.c.payer_id)
            .where(payers.c.payer_type.in_(query.payer_types))))
    if query.reasons and skip != 'reasons':
        conditions.append(transfers.c.reason.in_(query.reasons))
    return conditions


def _counts(connection: Connection, start: date, end: date, conditions):
    return dict(connection.execute(select(transfers.c.facility_id, func.count())
        .where(transfers.c.transfer_date.between(start, end), *conditions)
        .group_by(transfers.c.facility_id)).all())


def hospital_transfers(connection: Connection, query: TransfersQuery):
    if not _generated(connection, query.start_date, query.end_date):
        raise ApiError('summary_unavailable', 'The requested period includes days not generated yet. '
            'Run the seeder update or select completed dates.', 409)
    in_range = transfers.c.transfer_date.between(query.start_date, query.end_date)
    soon = transfers.c.days_since_admission <= WITHIN_DAYS
    totals = {row['facility_id']: row for row in connection.execute(
        select(transfers.c.facility_id, func.count().label('transfers'),
            func.count().filter(soon).label('within_30_days'),
            func.sum(transfers.c.days_since_admission).label('los_days'),
            func.count().filter(and_(soon, transfers.c.admission_source_type == 'Hospital')).label('rehospitalizations'))
        .where(in_range, *_filters(query)).group_by(transfers.c.facility_id)).mappings()}
    # The same number of days just before the range, with the same filters.
    prior_end = query.start_date - timedelta(days=1)
    prior_start = prior_end - timedelta(days=query.days - 1)
    prior = (_counts(connection, prior_start, prior_end, _filters(query))
        if _generated(connection, prior_start, prior_end) else None)
    # The two breakdowns, per facility, so the page scopes them as it scopes the
    # table; each applies the other's filter and keeps all of its own slices.
    by_payer, by_reason = {}, {}
    for facility_id, payer_type, count in connection.execute(
            select(transfers.c.facility_id, payers.c.payer_type, func.count())
            .select_from(transfers.join(payers, payers.c.payer_id == transfers.c.payer_id))
            .where(in_range, *_filters(query, skip='payers')).group_by(transfers.c.facility_id, payers.c.payer_type)):
        by_payer.setdefault(facility_id, {})[payer_type] = count
    for facility_id, reason, count in connection.execute(
            select(transfers.c.facility_id, transfers.c.reason, func.count())
            .where(in_range, *_filters(query, skip='reasons')).group_by(transfers.c.facility_id, transfers.c.reason)):
        by_reason.setdefault(facility_id, {})[reason] = count
    # A payer's rate divides by that payer's days.
    census_filters = [census.c.payer_type.in_(query.payer_types)] if query.payer_types else []
    resident_days = dict(connection.execute(
        select(census.c.facility_id, func.sum(census.c.closing_census))
        .where(census.c.summary_date.between(query.start_date, query.end_date), *census_filters)
        .group_by(census.c.facility_id)).all())

    items = []
    for location in connection.execute(facility_locations(LocationSelection())).mappings():
        row = totals.get(location['facility_id'], {})
        items.append(dict(facility_id=str(location['facility_id']), facility_name=location['facility_name'],
            state=location['state'], portfolio=location['portfolio_name'], region=location['region_name'],
            transfers=int(row.get('transfers', 0)), within_30_days=int(row.get('within_30_days', 0)),
            los_days=int(row.get('los_days', 0) or 0), rehospitalizations=int(row.get('rehospitalizations', 0)),
            resident_days=int(resident_days.get(location['facility_id'], 0) or 0),
            prior_transfers=None if prior is None else int(prior.get(location['facility_id'], 0)),
            payers=by_payer.get(location['facility_id'], {}), reasons=by_reason.get(location['facility_id'], {})))
    items.sort(key=lambda item: (item['state'], item['portfolio'], item['region'], item['facility_name']))
    return dict(start_date=query.start_date, end_date=query.end_date, prior_start_date=prior_start,
        prior_end_date=prior_end, items=items)


class DailyTransfersQuery(TransfersQuery):
    # The drilldown's facilities; empty means every facility.
    facility_ids: list[UUID] = Field(default_factory=list, max_length=1000)


class DailyTransfers(BaseModel):
    days: list[dict] = Field(description='Every day of the range: its date and transfers, zero included.')


def daily(connection: Connection, query: DailyTransfersQuery):
    """Each day's transfers for the trend: the same transfers and filters as the
    table, over the drilldown's facilities. A day with none is zero."""
    if not _generated(connection, query.start_date, query.end_date):
        raise ApiError('summary_unavailable', 'The requested period includes days not generated yet. '
            'Run the seeder update or select completed dates.', 409)
    conditions = _filters(query)
    if query.facility_ids:
        conditions.append(transfers.c.facility_id.in_(query.facility_ids))
    counts = dict(connection.execute(select(transfers.c.transfer_date, func.count())
        .where(transfers.c.transfer_date.between(query.start_date, query.end_date), *conditions)
        .group_by(transfers.c.transfer_date)).all())
    return dict(days=[dict(date=query.start_date + timedelta(days=offset),
            transfers=counts.get(query.start_date + timedelta(days=offset), 0))
        for offset in range(query.days)])
