"""monthly pdpm census facts

Revision: 0a01503e1031
Parent: 5c076e17011f
"""
from alembic import op
import sqlalchemy as sa


revision = '0a01503e1031'
down_revision = '5c076e17011f'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_pdpm_census_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('resident_days', sa.Integer(), nullable=False),
    sa.Column('actual_rates', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('factor_days', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint("payer_type IN ('medicare', 'managed_medicare_pdpm')"),
    sa.CheckConstraint('actual_rates > 0 AND factor_days > 0'),
    sa.CheckConstraint('resident_days > 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('month_start', 'facility_id', 'payer_type')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
