"""transfer logs

Revision: 0cd11a11357e
Parent: daa0a7e2bdb1
"""
from alembic import op
import sqlalchemy as sa


revision = '0cd11a11357e'
down_revision = 'daa0a7e2bdb1'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_logs',
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('days_since_admission', sa.Integer(), nullable=False),
    sa.Column('admission_source_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.CheckConstraint("reason IN ('Respiratory', 'Cardiac', 'Infection or sepsis', 'Urinary tract infection', 'Fall or injury', 'Change in mental status', 'Gastrointestinal', 'Dehydration or electrolytes', 'Surgical complication', 'Planned procedure', 'Other')", name='ck_transfer_logs_reason'),
    sa.CheckConstraint('days_since_admission >= 0'),
    sa.CheckConstraint('transfer_date >= admission_date'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('stay_id'),
    info={'description': 'One hospital transfer per row: each discharge to a hospital with its reason, payer, facility, days since admission and admission source, so clinical reports can cross any of them.'}
    )
    op.create_index('ix_transfer_logs_date', 'transfer_logs', ['transfer_date', 'facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
