"""medicaid assessments

Revision: 20cca0e0f183
Parent: 0a01503e1031
"""
from alembic import op
import sqlalchemy as sa


revision = '20cca0e0f183'
down_revision = '0a01503e1031'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicaid_assessments',
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('nursing_function_score', sa.SmallInteger(), nullable=False),
    sa.Column('ard', sa.Date(), nullable=False),
    sa.Column('coded_date', sa.Date(), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Y][A-F]$'"),
    sa.CheckConstraint('coded_date >= ard'),
    sa.CheckConstraint('nursing_function_score BETWEEN 0 AND 16', name='ck_medicaid_assessments_nursing_function_score'),
    sa.PrimaryKeyConstraint('payer_stay_id', 'segment')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
