"""add pdpm worksheet entries

Revision: 34f5da6f0060
Parent: febf9d4d5027
"""
from alembic import op
import sqlalchemy as sa


revision = '34f5da6f0060'
down_revision = 'febf9d4d5027'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdpm_worksheet_entries',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('reply_to', sa.Uuid(), nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(action = 'reply') = (reply_to IS NOT NULL)", name='ck_pdpm_worksheet_entries_reply'),
    sa.CheckConstraint("action <> 'reply' OR length(trim(note)) > 0", name='ck_pdpm_worksheet_entries_reply_note'),
    sa.CheckConstraint("action IN ('set', 'add', 'remove', 'reply')", name='ck_pdpm_worksheet_entries_action'),
    sa.ForeignKeyConstraint(['reply_to'], ['pdpm_worksheet_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('ix_pdpm_worksheet_entries_cell', 'pdpm_worksheet_entries', ['payer_stay_id', 'field', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
