"""add facility beds and bed assignments

Revision: 35de83e96bbf
Parent: dc6888918a12
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '35de83e96bbf'
down_revision = 'dc6888918a12'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_beds',
    sa.Column('bed_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('wing', sa.String(length=1), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('bed', sa.String(length=1), nullable=False),
    sa.CheckConstraint("bed IN ('A', 'B')"),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('facility_id', 'room', 'bed')
    )
    op.create_index('ix_facility_beds_facility', 'facility_beds', ['facility_id'], unique=False)
    op.create_table('bed_assignments',
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('move', sa.SmallInteger(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('bed_id', sa.Uuid(), nullable=True),
    sa.Column('in_bed', postgresql.DATERANGE(), nullable=False),
    sa.CheckConstraint('NOT isempty(in_bed) AND NOT lower_inf(in_bed)'),
    sa.ForeignKeyConstraint(['bed_id'], ['facility_beds.bed_id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('stay_id', 'move')
    )
    op.create_index('ix_bed_assignments_facility', 'bed_assignments', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
