"""add referring hospitals and monthly referral facts

Revision: 387dabdf88af
Parent: 6d5fb75b4371
"""
from alembic import op
import sqlalchemy as sa


revision = '387dabdf88af'
down_revision = '6d5fb75b4371'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referring_hospitals',
    sa.Column('hospital', sa.String(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(trim(hospital)) > 0'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('hospital'),
    info={'description': 'The hospitals that refer residents in, and the region each one refers into. State and portfolio are joins through regions, never stored copies.'}
    )
    op.create_index(op.f('ix_referring_hospitals_region_id'), 'referring_hospitals', ['region_id'], unique=False)
    op.create_table('monthly_referral_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('hospital', sa.String(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('admissions', sa.SmallInteger(), nullable=False),
    sa.Column('readmissions', sa.SmallInteger(), nullable=False),
    sa.Column('readmissions_30_day', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint('admissions > 0'),
    sa.CheckConstraint('readmissions BETWEEN 0 AND admissions'),
    sa.CheckConstraint('readmissions_30_day BETWEEN 0 AND readmissions'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['hospital'], ['referring_hospitals.hospital'], ),
    sa.PrimaryKeyConstraint('month_start', 'hospital', 'facility_id', 'payer_type'),
    info={'description': 'Calendar-month rollup of the hospital referrals in daily_admission_facts, at hospital/facility/payer-type grain. Flows only, so every column sums over any set of rows.'}
    )
    op.create_index('ix_monthly_referral_facts_hospital', 'monthly_referral_facts', ['hospital', 'month_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
