"""add census logs

Revision: 3da60bf99d37
Parent: 9923f970102e
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3da60bf99d37'
down_revision = '9923f970102e'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_logs',
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.SmallInteger(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('is_readmission', sa.Boolean(), nullable=False),
    sa.Column('care_level', sa.String(), nullable=False),
    sa.Column('skilled_day', sa.SmallInteger(), nullable=True),
    sa.Column('in_bed', postgresql.DATERANGE(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint("care_level IN ('Low', 'Moderate', 'High', 'Complex')"),
    sa.CheckConstraint('NOT isempty(in_bed) AND NOT lower_inf(in_bed)'),
    sa.CheckConstraint('daily_rate > 0'),
    sa.CheckConstraint('skilled_day IS NULL OR skilled_day >= 1'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.PrimaryKeyConstraint('payer_stay_id', 'segment')
    )
    op.create_index('ix_census_logs_in_bed', 'census_logs', ['in_bed'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
