"""progress notes

Revision: 3e4a6172d1e7
Parent: b954f000e417
"""
from alembic import op
import sqlalchemy as sa


revision = '3e4a6172d1e7'
down_revision = 'b954f000e417'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_notes',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('clinician', sa.String(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('flag_terms', sa.ARRAY(sa.String()), nullable=False),
    sa.CheckConstraint("note_type IN ('Nursing', 'Therapy', 'Physician', 'Dietary', 'Social Service', 'Activities')", name='ck_progress_notes_type'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index('ix_progress_notes_date', 'progress_notes', ['note_date', 'facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
