"""daily staffing facts

Revision: 4464b92222fb
Parent: 3e4a6172d1e7
"""
from alembic import op
import sqlalchemy as sa


revision = '4464b92222fb'
down_revision = '3e4a6172d1e7'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_staffing_facts',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('target_hours', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('excess_hours', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('short_hours', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('wages', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('excess_wages', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("role IN ('rn', 'lpn', 'cna', 'pt', 'pta', 'ot', 'cota', 'slp', 'dietary_aide', 'cook', 'evs')"),
    sa.CheckConstraint('hours_worked - target_hours = excess_hours - short_hours'),
    sa.CheckConstraint('hours_worked >= 0 AND target_hours >= 0 AND excess_hours >= 0 AND short_hours >= 0 AND wages >= 0 AND excess_wages >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('summary_date', 'facility_id', 'role'),
    info={'description': 'Hours worked, target hours and wages per facility, staffing role and day. Excess and short hours are measured each day, so a parent scope adds them up without one offsetting the other. PPD divides hours by daily_payer_census_facts closing census, summed.'}
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
