"""incident severity and hour

Revision: 4b11b9b41100
Parent: 7ae4c710ffd4
"""
from alembic import op
import sqlalchemy as sa


revision = '4b11b9b41100'
down_revision = '7ae4c710ffd4'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Required columns on a filled table fail without a default. The rows are
    # rebuilt whole, and the generator's rules changed with these columns, so
    # the same update rebuilds them.
    op.execute('TRUNCATE incident_logs')
    op.add_column('incident_logs', sa.Column('severity', sa.SmallInteger(), nullable=False))
    op.add_column('incident_logs', sa.Column('incident_hour', sa.SmallInteger(), nullable=False))
    # Autogenerate writes no CHECK constraints for an existing table; these are
    # the schema's, by hand.
    op.create_check_constraint('ck_incident_logs_severity', 'incident_logs', 'severity BETWEEN 1 AND 5')
    op.create_check_constraint('ck_incident_logs_hour', 'incident_logs', 'incident_hour BETWEEN 0 AND 23')
    op.create_check_constraint('ck_incident_logs_hospitalized_major', 'incident_logs', 'NOT hospitalized OR severity >= 4')
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
