"""add census days to monthly payer census

Revision: 526b7816817b
Parent: 35de83e96bbf
"""
from alembic import op
import sqlalchemy as sa


revision = '526b7816817b'
down_revision = '35de83e96bbf'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # The table is derived and rebuilt whole by every update, so it is emptied
    # rather than backfilled, and its checkpoints are cleared so the next update
    # rebuilds it with the new column. NOT NULL columns cannot be added to a
    # populated table without a default.
    op.execute('TRUNCATE monthly_payer_census_facts')
    op.execute("DELETE FROM sandbox_daily_runs WHERE generator = 'monthly_adt_summary'")
    op.execute("DELETE FROM sandbox_generator_runs WHERE name = 'monthly_adt_summary'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_payer_census_facts', sa.Column('census_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
