"""index pdpm assessments ard

Revision: 5c076e17011f
Parent: afc87f2cb5a7
"""
from alembic import op
import sqlalchemy as sa


revision = '5c076e17011f'
down_revision = 'afc87f2cb5a7'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pdpm_assessments_ard'), 'pdpm_assessments', ['ard'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
