"""weight logs

Revision: 64138e426d2c
Parent: ec4a68b6cabb
"""
from alembic import op
import sqlalchemy as sa


revision = '64138e426d2c'
down_revision = 'ec4a68b6cabb'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_logs',
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('weighed_on', sa.Date(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.CheckConstraint('weight BETWEEN 60 AND 400', name='ck_weight_logs_weight'),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('stay_id', 'weighed_on')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
