"""add payer change logs

Revision: 6d5fb75b4371
Parent: b9118554bbe8
"""
from alembic import op
import sqlalchemy as sa


revision = '6d5fb75b4371'
down_revision = 'b9118554bbe8'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payer_change_logs',
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('previous_payer_id', sa.Uuid(), nullable=False),
    sa.Column('new_payer_id', sa.Uuid(), nullable=False),
    sa.Column('previous_start_date', sa.Date(), nullable=False),
    sa.Column('new_end_date', sa.Date(), nullable=True),
    sa.Column('is_type_change', sa.Boolean(), nullable=False),
    sa.CheckConstraint('change_date > previous_start_date'),
    sa.CheckConstraint('new_end_date IS NULL OR new_end_date > change_date'),
    sa.CheckConstraint('previous_payer_id <> new_payer_id'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['new_payer_id'], ['payers.payer_id'], ),
    sa.ForeignKeyConstraint(['payer_stay_id'], ['res_payer_stays.payer_stay_id'], ),
    sa.ForeignKeyConstraint(['previous_payer_id'], ['payers.payer_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('payer_stay_id'),
    info={'description': 'One row per payer change, flattened with the period it moved from. Derived from res_payer_stays to spare every report the self-join on period_number - 1.'}
    )
    op.create_index(op.f('ix_payer_change_logs_change_date'), 'payer_change_logs', ['change_date'], unique=False)
    op.create_index('ix_payer_change_logs_facility', 'payer_change_logs', ['facility_id', 'change_date'], unique=False)
    op.create_index(op.f('ix_payer_change_logs_resident_id'), 'payer_change_logs', ['resident_id'], unique=False)
    op.create_index(op.f('ix_payer_change_logs_stay_id'), 'payer_change_logs', ['stay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
