"""add pdpm assessments

Revision: 6e0cb6c216ca
Parent: 526b7816817b
"""
from alembic import op
import sqlalchemy as sa


revision = '6e0cb6c216ca'
down_revision = '526b7816817b'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdpm_assessments',
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('pdpm_code', sa.String(length=4), nullable=False),
    sa.CheckConstraint("pdpm_code ~ '^[A-P][A-L][A-Y][A-F]$'"),
    sa.PrimaryKeyConstraint('payer_stay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
