"""add users

Revision: 6e3b41eed469
Parent: 9b86bcd20d0e
"""
from alembic import op
import sqlalchemy as sa


revision = '6e3b41eed469'
down_revision = '9b86bcd20d0e'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("password_hash LIKE '$2%%'"),
    sa.CheckConstraint('length(trim(username)) > 0'),
    sa.PrimaryKeyConstraint('user_id'),
    info={'description': 'Accounts permitted to read the reports. Passwords are stored only as bcrypt digests; the plaintext exists nowhere in the database or the repository.'}
    )
    op.create_index('ix_users_username', 'users', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
