"""add facility payer rates

Revision: 71ad7a7fb0f4
Parent: 6e3b41eed469
"""
from alembic import op
import sqlalchemy as sa


revision = '71ad7a7fb0f4'
down_revision = '6e3b41eed469'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_payer_rates',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('daily_rate > 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'payer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
