"""add depression flag to pdpm assessments

Revision: 7894c57a2aee
Parent: c891a59860c5
"""
from alembic import op
import sqlalchemy as sa


revision = '7894c57a2aee'
down_revision = 'c891a59860c5'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdpm_assessments', sa.Column('depression', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
