"""incident hospitalized

Revision: 7ae4c710ffd4
Parent: e5a6a968a42f
"""
from alembic import op
import sqlalchemy as sa


revision = '7ae4c710ffd4'
down_revision = 'e5a6a968a42f'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # A required column on a filled table fails without a default. The rows are
    # rebuilt whole, and the generator's rules changed with this column, so the
    # same update rebuilds them.
    op.execute('TRUNCATE incident_logs')
    op.add_column('incident_logs', sa.Column('hospitalized', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
