"""add discharge disposition and daily discharge facts

Revision: 811d1a1bd996
Parent: eb53a6aaddee
"""
from alembic import op
import sqlalchemy as sa


revision = '811d1a1bd996'
down_revision = 'eb53a6aaddee'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_discharge_facts',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('destination_type', sa.String(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('discharges', sa.Integer(), nullable=False),
    sa.Column('ama_discharges', sa.Integer(), nullable=False),
    sa.Column('length_of_stay_days', sa.Integer(), nullable=False),
    sa.CheckConstraint("destination_type IN ('Hospital', 'Skilled Nursing', 'Home', 'Rehab Facility', 'Assisted Living', 'Community', 'Funeral Home')"),
    sa.CheckConstraint('ama_discharges BETWEEN 0 AND discharges'),
    sa.CheckConstraint('discharges > 0'),
    sa.CheckConstraint('length(trim(destination_name)) > 0'),
    sa.CheckConstraint('length_of_stay_days >= discharges'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.PrimaryKeyConstraint('summary_date', 'facility_id', 'payer_id', 'destination_type', 'destination_name'),
    info={'description': 'Additive daily discharge measures at facility/payer/destination grain. Transfers and deaths are read back from destination_type; length of stay is a sum beside its count so any grouping divides correctly.'}
    )
    op.create_index('ix_daily_discharge_facts_facility', 'daily_discharge_facts', ['facility_id', 'summary_date'], unique=False)
    op.add_column('discharge_logs', sa.Column('is_ama', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###

    # Reviewed manual step: autogenerate writes CHECK constraints only inside
    # create_table, so this one has to be added by hand. No backfill is needed --
    # every existing row takes the false default, which already satisfies it.
    # AMA is not derivable from anything saved, so historical rows stay false
    # until discharge_logs --regenerate draws them.
    op.create_check_constraint('ck_discharge_logs_ama_exclusive', 'discharge_logs',
        "NOT (is_ama AND (is_deceased OR destination_type = 'Hospital'))")


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
