"""add SLP condition flags to pdpm assessments

Revision: 8701098fda9b
Parent: 858917c0a275
"""
from alembic import op
import sqlalchemy as sa


revision = '8701098fda9b'
down_revision = '858917c0a275'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdpm_assessments', sa.Column('acute_neuro', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pdpm_assessments', sa.Column('slp_comorbidity', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pdpm_assessments', sa.Column('cognitive_impairment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pdpm_assessments', sa.Column('mechanically_altered_diet', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pdpm_assessments', sa.Column('swallowing_disorder', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
