"""transfer hospital

Revision: 87b3236bd531
Parent: 0cd11a11357e
"""
from alembic import op
import sqlalchemy as sa


revision = '87b3236bd531'
down_revision = '0cd11a11357e'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # A required column on a filled table fails without a default. The rows are
    # rebuilt whole from discharge_logs, and the generator's rules changed with
    # this column, so the same update rebuilds them with their hospitals.
    op.execute('TRUNCATE transfer_logs')
    op.add_column('transfer_logs', sa.Column('hospital_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
