"""add monthly admission and discharge facts

Revision: 9b86bcd20d0e
Parent: 387dabdf88af
"""
from alembic import op
import sqlalchemy as sa


revision = '9b86bcd20d0e'
down_revision = '387dabdf88af'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_admission_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('admissions', sa.SmallInteger(), nullable=False),
    sa.Column('readmissions', sa.SmallInteger(), nullable=False),
    sa.Column('readmissions_30_day', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint("source_type IN ('Hospital', 'Skilled Nursing', 'Home', 'Rehab Facility', 'Assisted Living', 'Community')"),
    sa.CheckConstraint('admissions > 0'),
    sa.CheckConstraint('readmissions BETWEEN 0 AND admissions'),
    sa.CheckConstraint('readmissions_30_day BETWEEN 0 AND readmissions'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('month_start', 'facility_id', 'payer_type', 'source_type'),
    info={'description': 'Calendar-month rollup of daily_admission_facts at facility/payer-type/source-type grain, for monthly admissions trending by referral source. monthly_payer_census_facts carries monthly admissions too but has no source dimension and cannot gain one, because census is a level rather than a flow.'}
    )
    op.create_index('ix_monthly_admission_facts_facility', 'monthly_admission_facts', ['facility_id', 'month_start'], unique=False)
    op.create_table('monthly_discharge_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('destination_type', sa.String(), nullable=False),
    sa.Column('discharges', sa.SmallInteger(), nullable=False),
    sa.Column('ama_discharges', sa.SmallInteger(), nullable=False),
    sa.Column('length_of_stay_days', sa.Integer(), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint("destination_type IN ('Hospital', 'Skilled Nursing', 'Home', 'Rehab Facility', 'Assisted Living', 'Community', 'Funeral Home')"),
    sa.CheckConstraint('ama_discharges BETWEEN 0 AND discharges'),
    sa.CheckConstraint('discharges > 0'),
    sa.CheckConstraint('length_of_stay_days >= discharges'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('month_start', 'facility_id', 'payer_type', 'destination_type'),
    info={'description': 'Calendar-month rollup of daily_discharge_facts at facility/payer-type/destination-type grain, for monthly discharge trending by destination. Length of stay is a sum beside its count so any grouping divides correctly.'}
    )
    op.create_index('ix_monthly_discharge_facts_facility', 'monthly_discharge_facts', ['facility_id', 'month_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
