"""incident logs

Revision: a31923b71a0c
Parent: 87b3236bd531
"""
from alembic import op
import sqlalchemy as sa


revision = 'a31923b71a0c'
down_revision = '87b3236bd531'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_logs',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=False),
    sa.CheckConstraint("incident_type IN ('Fall', 'Skin tear or bruise', 'Medication error', 'Resident altercation', 'Pressure injury', 'Elopement or wandering', 'Choking', 'Other')", name='ck_incident_logs_type'),
    sa.CheckConstraint('closed_date > incident_date'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('incident_id'),
    info={'description': 'One resident incident per row, on a day the resident was in a bed, with its type and the day its investigation closed.'}
    )
    op.create_index('ix_incident_logs_date', 'incident_logs', ['incident_date', 'facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
