"""add daily payer census facts

Revision: a517067d9057
Parent: d29c787f353c
"""
from alembic import op
import sqlalchemy as sa


revision = 'a517067d9057'
down_revision = 'd29c787f353c'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_payer_census_facts',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('opening_census', sa.SmallInteger(), nullable=False),
    sa.Column('admissions', sa.SmallInteger(), nullable=False),
    sa.Column('discharges', sa.SmallInteger(), nullable=False),
    sa.Column('changes_in', sa.SmallInteger(), nullable=False),
    sa.Column('changes_out', sa.SmallInteger(), nullable=False),
    sa.Column('closing_census', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('closing_census = opening_census + admissions + changes_in - discharges - changes_out'),
    sa.CheckConstraint('opening_census >= 0 AND closing_census >= 0 AND admissions >= 0 AND discharges >= 0 AND changes_in >= 0 AND changes_out >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('summary_date', 'facility_id', 'payer_type'),
    info={'description': 'Daily census and movement by payer type: opening + admissions + changes in - discharges - changes out = closing. Sums back to adt_daily_census.'}
    )
    op.create_index('ix_daily_payer_census_facts_facility', 'daily_payer_census_facts', ['facility_id', 'summary_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
