"""add monthly payer census facts

Revision: b9118554bbe8
Parent: a517067d9057
"""
from alembic import op
import sqlalchemy as sa


revision = 'b9118554bbe8'
down_revision = 'a517067d9057'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_payer_census_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('opening_census', sa.SmallInteger(), nullable=False),
    sa.Column('admissions', sa.SmallInteger(), nullable=False),
    sa.Column('discharges', sa.SmallInteger(), nullable=False),
    sa.Column('changes_in', sa.SmallInteger(), nullable=False),
    sa.Column('changes_out', sa.SmallInteger(), nullable=False),
    sa.Column('closing_census', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint('closing_census = opening_census + admissions + changes_in - discharges - changes_out'),
    sa.CheckConstraint('opening_census >= 0 AND closing_census >= 0 AND admissions >= 0 AND discharges >= 0 AND changes_in >= 0 AND changes_out >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('month_start', 'facility_id', 'payer_type'),
    info={'description': 'Calendar-month rollup of daily_payer_census_facts for monthly trending. Flows are summed; census is taken from the first and last day of each month.'}
    )
    op.create_index('ix_monthly_payer_census_facts_facility', 'monthly_payer_census_facts', ['facility_id', 'month_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
