"""weight logs running values

Revision: b954f000e417
Parent: 64138e426d2c
"""
from alembic import op
import sqlalchemy as sa


revision = 'b954f000e417'
down_revision = '64138e426d2c'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # The new columns are NOT NULL and computed by the generator, whose rules
    # changed with them: update rebuilds the table right after this.
    op.execute('TRUNCATE weight_logs')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_logs', sa.Column('admission_weight', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('weight_logs', sa.Column('highest', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('weight_logs', sa.Column('lowest', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('weight_logs', sa.Column('weight_30_days_before', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('weight_logs', sa.Column('weight_180_days_before', sa.Numeric(precision=5, scale=1), nullable=True))
    op.create_check_constraint('ck_weight_logs_range', 'weight_logs', 'lowest <= weight AND weight <= highest')
    op.create_index('ix_weight_logs_weighed_on', 'weight_logs', ['weighed_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
