"""add nursing function score to pdpm assessments

Revision: c891a59860c5
Parent: 8701098fda9b
"""
from alembic import op
import sqlalchemy as sa


revision = 'c891a59860c5'
down_revision = '8701098fda9b'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdpm_assessments', sa.Column('nursing_function_score', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # Autogenerate does not write CHECK constraints.
    op.create_check_constraint('ck_pdpm_assessments_nursing_function_score', 'pdpm_assessments',
        'nursing_function_score BETWEEN 0 AND 16')


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
