"""add daily payer change facts

Revision: d29c787f353c
Parent: 811d1a1bd996
"""
from alembic import op
import sqlalchemy as sa


revision = 'd29c787f353c'
down_revision = '811d1a1bd996'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_payer_change_facts',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('previous_payer_type', sa.String(), nullable=False),
    sa.Column('new_payer_type', sa.String(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.CheckConstraint('changes > 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('summary_date', 'facility_id', 'previous_payer_type', 'new_payer_type'),
    info={'description': 'Additive daily payer-change counts at facility/from-type/to-type grain. Residents affected is a distinct count and is read from res_payer_stays instead.'}
    )
    op.create_index('ix_daily_payer_change_facts_facility', 'daily_payer_change_facts', ['facility_id', 'summary_date'], unique=False)
    op.create_index('ix_res_payer_stays_changes', 'res_payer_stays', ['start_date', 'stay_id'], unique=False, postgresql_where=sa.text('period_number > 1'))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
