"""monthly medicaid census facts

Revision: daa0a7e2bdb1
Parent: 20cca0e0f183
"""
from alembic import op
import sqlalchemy as sa


revision = 'daa0a7e2bdb1'
down_revision = '20cca0e0f183'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_medicaid_census_facts',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('resident_days', sa.Integer(), nullable=False),
    sa.Column('actual_rates', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint("date_trunc('month', month_start) = month_start"),
    sa.CheckConstraint('actual_rates >= 0'),
    sa.CheckConstraint('resident_days > 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('month_start', 'facility_id')
    )
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
