"""store names on resident summaries

Revision: dc6888918a12
Parent: dfa59f6c594f
"""
from alembic import op
import sqlalchemy as sa


revision = 'dc6888918a12'
down_revision = 'dfa59f6c594f'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # The table is derived and rebuilt whole by every update, so it is emptied
    # rather than backfilled, and its checkpoints are cleared so the next update
    # rebuilds it with the new columns. NOT NULL columns cannot be added to a
    # populated table without a default.
    op.execute('TRUNCATE resident_summaries')
    op.execute("DELETE FROM sandbox_daily_runs WHERE generator = 'resident_summaries'")
    op.execute("DELETE FROM sandbox_generator_runs WHERE name = 'resident_summaries'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident_summaries', sa.Column('resident_name', sa.String(), nullable=False))
    op.add_column('resident_summaries', sa.Column('facility_name', sa.String(), nullable=False))
    op.add_column('resident_summaries', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('resident_summaries', sa.Column('portfolio', sa.String(), nullable=False))
    op.add_column('resident_summaries', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
