"""add resident summaries

Revision: dfa59f6c594f
Parent: ecb09a90bdcc
"""
from alembic import op
import sqlalchemy as sa


revision = 'dfa59f6c594f'
down_revision = 'ecb09a90bdcc'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident_summaries',
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('stays', sa.SmallInteger(), nullable=False),
    sa.Column('admissions', sa.SmallInteger(), nullable=False),
    sa.Column('discharges', sa.SmallInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('days_in_facility', sa.Integer(), nullable=False),
    sa.Column('payers', sa.SmallInteger(), nullable=False),
    sa.Column('payer_types', sa.SmallInteger(), nullable=False),
    sa.Column('first_admission', sa.Date(), nullable=False),
    sa.Column('last_admission', sa.Date(), nullable=False),
    sa.Column('last_discharge', sa.Date(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.CheckConstraint('days_in_facility >= 0 AND payers >= 1 AND payer_types BETWEEN 1 AND payers'),
    sa.CheckConstraint('is_current = (discharges < stays)'),
    sa.CheckConstraint('stays >= 1 AND admissions = stays AND discharges BETWEEN 0 AND stays'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], ),
    sa.PrimaryKeyConstraint('resident_id')
    )
    op.create_index('ix_resident_summaries_facility', 'resident_summaries', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
