"""incident payer

Revision: e5a6a968a42f
Parent: a31923b71a0c
"""
from alembic import op
import sqlalchemy as sa


revision = 'e5a6a968a42f'
down_revision = 'a31923b71a0c'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # A required column on a filled table fails without a default. The rows are
    # rebuilt whole from saved stays, and the generator's rules changed with this
    # column, so the same update rebuilds them with their payers.
    op.execute('TRUNCATE incident_logs')
    op.add_column('incident_logs', sa.Column('payer_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'incident_logs', 'payers', ['payer_id'], ['payer_id'])
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
