"""replace admission summaries with daily_admission_facts

Revision: eb53a6aaddee
Parent: 0002_medicaid_applications
"""
from alembic import op
import sqlalchemy as sa


revision = 'eb53a6aaddee'
down_revision = '0002_medicaid_applications'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_admission_facts',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('admissions', sa.Integer(), nullable=False),
    sa.Column('readmissions', sa.Integer(), nullable=False),
    sa.Column('readmissions_30_day', sa.Integer(), nullable=False),
    sa.Column('medicaid_pending_admissions', sa.Integer(), nullable=False),
    sa.CheckConstraint("source_type IN ('Hospital', 'Skilled Nursing', 'Home', 'Rehab Facility', 'Assisted Living', 'Community')"),
    sa.CheckConstraint('admissions > 0'),
    sa.CheckConstraint('length(trim(source_name)) > 0'),
    sa.CheckConstraint('medicaid_pending_admissions BETWEEN 0 AND admissions'),
    sa.CheckConstraint('readmissions BETWEEN 0 AND admissions'),
    sa.CheckConstraint('readmissions_30_day BETWEEN 0 AND readmissions'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ),
    sa.PrimaryKeyConstraint('summary_date', 'facility_id', 'payer_id', 'source_type', 'source_name'),
    info={'description': 'Additive daily admission measures at facility/payer/source grain. Reports group these rows; parent scopes are not stored.'}
    )
    op.create_index('ix_daily_admission_facts_facility', 'daily_admission_facts', ['facility_id', 'summary_date'], unique=False)
    # ### end Alembic commands ###

    # Reviewed manual steps. Autogenerate never drops a table, and the replacement
    # is derived entirely from admission_logs, so the old JSON payloads are not
    # migrated: they are rebuilt from source. Clearing the handler's checkpoints
    # makes the next update regenerate every date into the new table.
    op.drop_table('daily_admission_summaries')
    op.execute("DELETE FROM sandbox_daily_runs WHERE generator = 'admissions_summary'")
    op.execute("DELETE FROM sandbox_generator_runs WHERE name = 'admissions_summary'")


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
