"""infection logs

Revision: ec4a68b6cabb
Parent: 4b11b9b41100
"""
from alembic import op
import sqlalchemy as sa


revision = 'ec4a68b6cabb'
down_revision = '4b11b9b41100'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infection_logs',
    sa.Column('infection_id', sa.Uuid(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('wing', sa.String(), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=False),
    sa.Column('infection_type', sa.String(), nullable=False),
    sa.Column('fever', sa.Boolean(), nullable=False),
    sa.CheckConstraint("infection_type <> 'Fever, source unknown' OR fever", name='ck_infection_logs_fever'),
    sa.CheckConstraint("infection_type IN ('Respiratory', 'Influenza-like illness', 'Gastrointestinal', 'Urinary tract', 'Skin or soft tissue', 'Fever, source unknown')", name='ck_infection_logs_type'),
    sa.CheckConstraint('resolved_date > onset_date', name='ck_infection_logs_resolved'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['res_stays.stay_id'], ),
    sa.PrimaryKeyConstraint('infection_id'),
    info={'description': 'One resident infection or unexplained fever per row, with its type, fever, the wing the resident was in, and onset and resolved dates. Sporadic cases and outbreaks; the alert board finds outbreaks by its own rule.'}
    )
    op.create_index('ix_infection_logs_onset', 'infection_logs', ['onset_date', 'facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
