"""move pdpm rates out of census logs

Revision: ecb09a90bdcc
Parent: 3da60bf99d37
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ecb09a90bdcc'
down_revision = '3da60bf99d37'
branch_labels = None
depends_on = None
# List any immutable helper/data files imported by this revision, relative to migrations/.
artifacts = ()
# For a later NOT NULL/drop/constraint migration that requires earlier data work.
required_backfills = ()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdpm_rate_logs',
    sa.Column('payer_stay_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False),
    sa.Column('skilled_day', sa.SmallInteger(), nullable=False),
    sa.Column('in_effect', postgresql.DATERANGE(), nullable=False),
    sa.Column('pdpm_factor', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('NOT isempty(in_effect) AND NOT lower_inf(in_effect)'),
    sa.CheckConstraint('pdpm_factor > 0 AND daily_rate > 0'),
    sa.CheckConstraint('skilled_day >= 1'),
    sa.PrimaryKeyConstraint('payer_stay_id', 'step')
    )
    op.create_index('ix_pdpm_rate_logs_in_effect', 'pdpm_rate_logs', ['in_effect'], unique=False, postgresql_using='gist')
    op.drop_column('census_logs', 'skilled_day')
    # ### end Alembic commands ###


def downgrade():
    raise ValueError('Use a new corrective migration; automatic downgrades are disabled.')
